# Generated by Django 4.2.2 on 2024-09-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricerecord',
            unique_together={('item_number', 'account_name')},
        ),
        migrations.RemoveField(
            model_name='pricerecord',
            name='uom',
        ),
    ]
